fos_http_cache:
  cache_control:
    defaults:
      overwrite: true
    rules:
      -
        match:
          attributes: { _route: price_list|all_services_in_departments|services_by_department|employee.list|employee.details|employee.details.ehealth|employee.list.ehealth }
        headers:
          reverse_proxy_ttl: 1800
          cache_control: { public: true, max_age: 1800, s_maxage: 1800 }
          etag: "strong"
      -
        match:
          attributes: { _route: patient.profile_exists|patient.profile|patient.profile.declaration }
        headers:
          reverse_proxy_ttl: 30
          cache_control: { public: true, max_age: 30, s_maxage: 30 }
          etag: "strong"

      # 1 minute 60
      # 0,5 hour 1800
      # 2 hours 7200
      # 4 hours 14400
      # 1 day 86400

